"""Tier 2 (levels 5-10, "Heroes of the Realm") curated monster/NPC
archetypes. Bounded, curated set -- not a full SRD bestiary."""

MONSTERS = [
    {
        "name": "Ogre",
        "ac": 11,
        "hp": "59 (7d10+21)",
        "attack": "+6 to hit, 2d8+4 bludgeoning (greatclub)",
        "signature_ability": "None -- a raw, brutal melee threat.",
        "antagonist_archetype_keys": ["defiant_general", "rival_mercenary_company"],
    },
    {
        "name": "Bugbear War Leader",
        "ac": 16,
        "hp": "65 (10d8+20)",
        "attack": "+5 to hit, 2d8+3 slashing (morningstar), advantage if target hasn't acted yet this turn",
        "signature_ability": "Surprise Attack: +2d6 damage against a surprised target.",
        "antagonist_archetype_keys": ["defiant_general", "rival_mercenary_company", "smuggler_king"],
    },
    {
        "name": "Green Hag",
        "ac": 17,
        "hp": "82 (11d8+33)",
        "attack": "+6 to hit, 2d8+4 slashing (claws)",
        "signature_ability": "Mimicry: perfectly imitates voices and sounds; Illusory Appearance to disguise itself.",
        "antagonist_archetype_keys": ["ancient_spirit", "cult_leader"],
    },
    {
        "name": "Young Dragon",
        "ac": 18,
        "hp": "178 (17d10+85)",
        "attack": "+8 to hit, 2d10+5 (bite) plus a breath weapon (recharges on a roll of 5-6) dealing heavy elemental damage in an area",
        "signature_ability": "Frightful Presence: nearby creatures must save or be frightened.",
        "antagonist_archetype_keys": ["defiant_general", "self_styled_prophet"],
    },
    {
        "name": "Veteran",
        "ac": 17,
        "hp": "58 (9d8+18)",
        "attack": "+5 to hit, 2d6+3 slashing (longsword), two attacks per round",
        "signature_ability": "None -- a highly trained, disciplined fighter.",
        "antagonist_archetype_keys": ["fallen_noble", "corrupt_guild_master"],
    },
    {
        "name": "Priest",
        "ac": 13,
        "hp": "27 (5d8+5)",
        "attack": "Casts guiding bolt (+5 to hit, 4d6 radiant) or minor buffs/heals on allies",
        "signature_ability": "Divine Eminence: can empower a melee hit with extra radiant damage.",
        "antagonist_archetype_keys": ["cult_leader", "self_styled_prophet"],
    },
    {
        "name": "Mage",
        "ac": 12,
        "hp": "40 (9d8)",
        "attack": "Casts fire bolt (+5 to hit, 2d10 fire) or other prepared spells",
        "signature_ability": "Arcane utility: shield, misty step, or a controlling spell as a defensive reaction.",
        "antagonist_archetype_keys": ["spymaster", "corrupt_guild_master"],
    },
    {
        "name": "Doppelganger",
        "ac": 14,
        "hp": "52 (8d8+16)",
        "attack": "+4 to hit, 1d6+2 bludgeoning (slam), two attacks per round",
        "signature_ability": "Shapechanger: can perfectly assume the appearance of a specific humanoid it has seen.",
        "antagonist_archetype_keys": ["spymaster"],
    },
    {
        "name": "Ghost",
        "ac": 11,
        "hp": "45 (10d8)",
        "attack": "+5 to hit, 4d6+2 necrotic (withering touch), can possess a humanoid",
        "signature_ability": "Etherealness: can pass through walls and become invisible.",
        "antagonist_archetype_keys": ["ancient_spirit"],
    },
    {
        "name": "Werewolf",
        "ac": 12,
        "hp": "58 (9d8+18)",
        "attack": "+4 to hit, 2d4+2 piercing (bite, can curse the target with lycanthropy) or 2d8+2 slashing (claws in wolf/hybrid form)",
        "signature_ability": "Regenerates each turn unless hit by a silvered weapon.",
        "antagonist_archetype_keys": ["plague_hivemind", "ancient_spirit"],
    },
]
