"""SRD 4th-level spells. Authored incrementally -- see cantrips.py."""

SPELLS_LEVEL_4 = {
    "Ice Storm": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "300 feet",
        "duration": "Instantaneous",
        "classes": ["Druid", "Sorcerer", "Wizard"],
        "description": "Hail pounds a 20-foot cylinder; each creature there makes a Dexterity save, taking 2d8 bludgeoning + 4d6 cold damage (half on success).",
    },
    "Wall of Fire": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Druid", "Sorcerer", "Wizard"],
        "description": "Creates a wall of fire; creatures that end their turn near it or pass through take 5d8 fire damage (Dexterity save for half).",
    },
    "Greater Invisibility": {
        "school": "Illusion",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Sorcerer", "Wizard"],
        "description": "A touched creature turns invisible and stays invisible even while attacking or casting spells, while concentration holds.",
    },
    "Polymorph": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Bard", "Druid", "Sorcerer", "Wizard"],
        "description": "Transforms a target into a beast form on a failed Wisdom save (or willingly); its game statistics are replaced by the beast's while concentration holds.",
    },
    "Dominate Beast": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Druid", "Sorcerer"],
        "description": "A beast fails a Wisdom save and becomes charmed, obeying the caster's telepathic commands while concentration holds.",
    },
    "Guardian of Faith": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "8 hours",
        "classes": ["Cleric"],
        "description": "Summons a large spectral guardian that deals 20 radiant damage to a hostile creature entering its space, until it has dealt 60 total damage.",
    },
    "Death Ward": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "8 hours",
        "classes": ["Cleric", "Paladin"],
        "description": "The first time a warded creature would drop to 0 HP, it instead drops to 1 HP -- a one-time save against death.",
    },
    "Freedom of Movement": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "8 hours",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Ranger"],
        "description": "A touched creature ignores difficult terrain and can't be paralyzed or restrained (automatically escapes a grapple).",
    },
    "Banishment": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Cleric", "Sorcerer", "Warlock", "Wizard"],
        "description": "A target vanishes to a harmless demiplane (native creatures) or its home plane (others) on a failed Charisma save, while concentration holds.",
    },
    "Confusion": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "90 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Druid", "Sorcerer", "Wizard"],
        "description": "Creatures in an area act randomly (wander off, attack the nearest creature, or do nothing) on a failed Wisdom save, repeating each turn.",
    },
    "Stoneskin": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Artificer", "Druid", "Sorcerer", "Wizard"],
        "description": "A touched creature gains resistance to nonmagical bludgeoning, piercing, and slashing damage while concentration holds.",
    },
    "Fire Shield": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Self",
        "duration": "10 minutes",
        "classes": ["Sorcerer", "Wizard"],
        "description": "The caster gains resistance to a chosen damage type (cold or fire) and any creature that hits them in melee takes 2d8 damage of the opposite type.",
    },
}
