"""SRD 3rd-level spells. Authored incrementally -- see cantrips.py."""

SPELLS_LEVEL_3 = {
    "Fireball": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "150 feet",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": "A classic explosive burst of flame in a 20-foot radius; each creature there makes a Dexterity save, taking 8d6 fire damage (half on success).",
    },
    "Lightning Bolt": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Self (100-foot line)",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": "A line of lightning; each creature in the line makes a Dexterity save, taking 8d6 lightning damage (half on success).",
    },
    "Counterspell": {
        "school": "Abjuration",
        "casting_time": "1 reaction",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Warlock", "Wizard"],
        "description": "Reaction as another creature casts a spell: automatically interrupts it if it's 3rd level or lower, otherwise an ability check to interrupt a higher-level spell.",
    },
    "Fly": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Artificer", "Sorcerer", "Warlock", "Wizard"],
        "description": "A touched creature gains a flying speed of 60 feet while concentration holds.",
    },
    "Haste": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Artificer", "Sorcerer", "Wizard"],
        "description": "A target's speed doubles, it gains +2 AC, advantage on Dexterity saves, and an extra action limited to Attack/Dash/Disengage/Hide/Use an Object, while concentration holds.",
    },
    "Spirit Guardians": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "Self (15-foot radius)",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Cleric"],
        "description": "Spectral guardians swirl around the caster; enemies that enter or start their turn nearby take 3d8 radiant or necrotic damage (Wisdom save for half) and have halved speed there.",
    },
    "Revivify": {
        "school": "Necromancy",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Cleric", "Paladin"],
        "description": "Returns a creature dead no longer than 1 minute to life with 1 hit point -- no effect on a creature dead longer than that.",
    },
    "Dispel Magic": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
        "description": "Ends spells currently affecting a target (automatically for spells of 3rd level or lower, an ability check for higher-level ones).",
    },
    "Vampiric Touch": {
        "school": "Necromancy",
        "casting_time": "1 action",
        "range": "Self",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Warlock", "Wizard"],
        "description": "Melee spell attack dealing 3d6 necrotic damage; the caster regains half the damage dealt as hit points. Repeatable each turn while concentration holds.",
    },
    "Animate Dead": {
        "school": "Necromancy",
        "casting_time": "1 minute",
        "range": "10 feet",
        "duration": "Instantaneous",
        "classes": ["Cleric", "Wizard"],
        "description": "Raises a skeleton or zombie from a corpse to fight under the caster's command until destroyed or the caster casts this spell again.",
    },
    "Call Lightning": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Druid"],
        "description": "Calls a storm cloud overhead; each turn a bolt can strike a point below it, dealing 3d10 lightning damage (Dexterity save for half) to creatures near the strike.",
    },
    "Conjure Animals": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Druid", "Ranger"],
        "description": "Summons a small group of fey spirits in beast form to fight alongside the caster for the duration.",
    },
    "Daylight": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "1 hour",
        "classes": ["Artificer", "Cleric", "Druid", "Paladin", "Sorcerer"],
        "description": "Creates a 60-foot radius of bright light that dispels magical darkness it overlaps. No direct damage, but strong utility against darkness-based enemies.",
    },
    "Hypnotic Pattern": {
        "school": "Illusion",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Sorcerer", "Warlock", "Wizard"],
        "description": "A twisting pattern of colors incapacitates creatures in an area on a failed Wisdom save, for as long as concentration holds -- a strong crowd-control option against groups.",
    },
    "Slow": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Sorcerer", "Wizard"],
        "description": "Up to six creatures in an area have halved speed, -2 AC and Dexterity saves, and can only take an action or bonus action (not both) on a failed Wisdom save.",
    },
}
