"""SRD 5th-level spells. Authored incrementally -- see cantrips.py."""

SPELLS_LEVEL_5 = {
    "Cone of Cold": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Self (60-foot cone)",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": "A blast of freezing air; each creature in the cone makes a Constitution save, taking 8d8 cold damage (half on success).",
    },
    "Wall of Force": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Wizard"],
        "description": "Creates an invisible wall of force nothing can physically or magically pass through (short of a wish spell) while concentration holds.",
    },
    "Hold Monster": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "90 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Sorcerer", "Warlock", "Wizard"],
        "description": "Like Hold Person but works on any creature type, not just humanoids -- paralyzed on a failed Wisdom save, repeating the save each turn.",
    },
    "Mass Cure Wounds": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Bard", "Cleric", "Druid"],
        "description": "Up to six creatures in an area each regain 3d8 + the caster's spellcasting modifier hit points.",
    },
    "Raise Dead": {
        "school": "Necromancy",
        "casting_time": "1 hour",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Cleric", "Paladin"],
        "description": "Returns a creature dead no more than 10 days to life, closing all instantly-fatal wounds but not curing other lingering afflictions.",
    },
    "Flame Strike": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Cleric"],
        "description": "A column of divine fire; each creature in the area makes a Dexterity save, taking 4d6 fire + 4d6 radiant damage (half on success).",
    },
    "Insect Plague": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "300 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Cleric", "Druid", "Sorcerer"],
        "description": "A swarm of biting insects fills an area; creatures there take 4d10 piercing damage on a failed Constitution save (half on success).",
    },
    "Dominate Person": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Sorcerer", "Wizard"],
        "description": "A humanoid target fails a Wisdom save and becomes charmed, obeying the caster's telepathic commands while concentration holds.",
    },
    "Contagion": {
        "school": "Necromancy",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "7 days",
        "classes": ["Cleric", "Druid"],
        "description": "A melee touch inflicts a magical disease that worsens over failed saves, eventually crippling an ability score's checks/saves.",
    },
    "Commune": {
        "school": "Divination",
        "casting_time": "1 minute",
        "range": "Self",
        "duration": "1 minute",
        "classes": ["Cleric"],
        "description": "Asks a deity/proxy up to three yes-or-no questions. No combat use, but a strong information tool between adventures.",
    },
    "Swift Quiver": {
        "school": "Transmutation",
        "casting_time": "1 bonus action",
        "range": "Touch",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Ranger"],
        "description": "A touched quiver conjures endless ammunition and lets the wielder make two additional ranged weapon attacks each turn as a bonus action.",
    },
}
