"""SRD 1st-level spells. Authored incrementally -- see cantrips.py."""

SPELLS_LEVEL_1 = {
    "Magic Missile": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": (
            "Three darts of magical force automatically hit (no attack "
            "roll), each dealing 1d4+1 force damage; can split darts "
            "between targets."
        ),
    },
    "Shield": {
        "school": "Abjuration",
        "casting_time": "1 reaction",
        "range": "Self",
        "duration": "1 round",
        "classes": ["Sorcerer", "Wizard"],
        "description": (
            "Reaction when hit or targeted: +5 AC until the start of your "
            "next turn (can turn a hit into a miss), also blocks magic "
            "missile entirely."
        ),
    },
    "Burning Hands": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Self (15-foot cone)",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": (
            "A cone of fire; each creature in the area makes a Dexterity "
            "save, taking 3d6 fire damage on a fail or half on a success."
        ),
    },
    "Detect Magic": {
        "school": "Divination",
        "casting_time": "1 action",
        "range": "Self",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
        "description": "Senses the presence and school of magic within 30 feet. No combat effect.",
    },
    "Cure Wounds": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Ranger"],
        "description": "A touched creature regains 1d8 + the caster's spellcasting modifier hit points.",
    },
    "Healing Word": {
        "school": "Evocation",
        "casting_time": "1 bonus action",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Bard", "Cleric", "Druid"],
        "description": "A creature at range regains 1d4 + the caster's spellcasting modifier hit points -- a bonus action, so it doesn't cost the caster their turn.",
    },
    "Bless": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Cleric", "Paladin"],
        "description": "Up to three chosen creatures add 1d4 to attack rolls and saving throws while concentration holds.",
    },
    "Guiding Bolt": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "1 round",
        "classes": ["Cleric"],
        "description": "Ranged spell attack for 4d6 radiant damage; the next attack roll against the target before the end of its next turn has advantage.",
    },
    "Command": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "1 round",
        "classes": ["Cleric", "Paladin"],
        "description": "A target that can hear/understand the caster must obey a one-word command (e.g. Drop, Flee, Grovel) on a failed Wisdom save.",
    },
    "Sanctuary": {
        "school": "Abjuration",
        "casting_time": "1 bonus action",
        "range": "30 feet",
        "duration": "1 minute",
        "classes": ["Cleric"],
        "description": "A warded creature can't be targeted by an attacker's attacks/harmful spells unless the attacker succeeds a Wisdom save first.",
    },
    "Bane": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Cleric"],
        "description": "Up to three targets subtract 1d4 from attack rolls and saving throws on a failed Charisma save, while concentration holds.",
    },
    "Inflict Wounds": {
        "school": "Necromancy",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Cleric"],
        "description": "Melee spell attack; on a hit deals 3d10 necrotic damage.",
    },
    "Entangle": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "90 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Druid", "Ranger"],
        "description": "Grasping weeds/vines fill an area; creatures there make a Strength save or become restrained, and the area is difficult terrain.",
    },
    "Faerie Fire": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Druid"],
        "description": "Outlines creatures in an area with light on a failed Dexterity save; attack rolls against them have advantage while outlined.",
    },
    "Goodberry": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Druid", "Ranger"],
        "description": "Creates ten berries; each restores 1 hit point and a day's food when eaten. Minor sustained healing, not burst.",
    },
    "Thunderwave": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "Self (15-foot cube)",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Bard", "Druid", "Sorcerer", "Wizard"],
        "description": "A wave of thunderous force; each creature in the area makes a Constitution save, taking 2d8 thunder damage (half on success) and being pushed 10 feet on a fail.",
    },
    "Charm Person": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "1 hour",
        "classes": ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
        "description": "A humanoid target regards the caster as a friendly acquaintance on a failed Wisdom save. Social utility, not direct damage.",
    },
    "Sleep": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "90 feet",
        "duration": "1 minute",
        "classes": ["Bard", "Sorcerer", "Wizard"],
        "description": "Puts creatures in an area to sleep, weakest-HP-first, up to a total of 5d8 hit points worth of creatures -- very strong against low-HP mobs, useless against a single tough target.",
    },
    "Chromatic Orb": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "90 feet",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": "A hurled sphere of energy in a damage type chosen by the caster (acid/cold/fire/lightning/poison/thunder); ranged spell attack for 3d8 damage.",
    },
    "Witch Bolt": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Sorcerer", "Warlock", "Wizard"],
        "description": "Ranged spell attack for 1d12 lightning damage; while concentrating, can deal the same damage again each turn without a new attack roll, as long as the target stays in range.",
    },
    "Hex": {
        "school": "Enchantment",
        "casting_time": "1 bonus action",
        "range": "90 feet",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Warlock"],
        "description": "Curses a target: the caster's weapon hits against it deal an extra 1d6 necrotic damage, and it has disadvantage on ability checks with a chosen ability.",
    },
    "Armor of Agathys": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "Self",
        "duration": "1 hour",
        "classes": ["Warlock"],
        "description": "Grants 5 temporary hit points; while any remain, a creature that hits the caster with a melee attack takes 5 cold damage.",
    },
    "Hellish Rebuke": {
        "school": "Evocation",
        "casting_time": "1 reaction",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Warlock"],
        "description": "Reaction when damaged by a creature within range: it makes a Dexterity save, taking 2d10 fire damage on a fail or half on a success.",
    },
    "Heroism": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Bard", "Paladin"],
        "description": "A willing touched creature is immune to being frightened and gains temporary hit points at the start of each of its turns while concentration holds.",
    },
    "Dissonant Whispers": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Bard"],
        "description": "Whispers a discordant melody into a target's mind; on a failed Wisdom save it takes 3d6 psychic damage and must immediately use its reaction to flee.",
    },
    "Shield of Faith": {
        "school": "Abjuration",
        "casting_time": "1 bonus action",
        "range": "60 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Cleric", "Paladin"],
        "description": "A shimmering field grants a target +2 AC while concentration holds.",
    },
    "Divine Favor": {
        "school": "Evocation",
        "casting_time": "1 bonus action",
        "range": "Self",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Paladin"],
        "description": "The caster's weapon attacks deal an extra 1d4 radiant damage while concentration holds.",
    },
    "Hunter's Mark": {
        "school": "Divination",
        "casting_time": "1 bonus action",
        "range": "90 feet",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Ranger"],
        "description": "Marks a target: the caster's weapon attacks against it deal an extra 1d6 damage, and the caster has advantage on Perception/Survival checks to find it.",
    },
    "Feather Fall": {
        "school": "Transmutation",
        "casting_time": "1 reaction",
        "range": "60 feet",
        "duration": "1 minute",
        "classes": ["Artificer", "Bard", "Sorcerer", "Wizard"],
        "description": "Up to five falling creatures slow to a harmless descent. No combat damage, but frequently narratively load-bearing.",
    },
}
