"""SRD 2nd-level spells. Authored incrementally -- see cantrips.py."""

SPELLS_LEVEL_2 = {
    "Scorching Ray": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Wizard"],
        "description": "Three rays of fire, each a separate ranged spell attack for 2d6 fire damage; can target one creature or split between several.",
    },
    "Misty Step": {
        "school": "Conjuration",
        "casting_time": "1 bonus action",
        "range": "Self",
        "duration": "Instantaneous",
        "classes": ["Sorcerer", "Warlock", "Wizard"],
        "description": "Teleports the caster up to 30 feet to an unoccupied space they can see -- an escape or repositioning tool, no damage.",
    },
    "Invisibility": {
        "school": "Illusion",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
        "description": "A touched creature becomes invisible while concentration holds, until it attacks or casts a spell.",
    },
    "Web": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Sorcerer", "Wizard"],
        "description": "Fills an area with sticky webbing; creatures there make a Dexterity save or become restrained, and the area is heavily obscured difficult terrain.",
    },
    "Mirror Image": {
        "school": "Illusion",
        "casting_time": "1 action",
        "range": "Self",
        "duration": "1 minute",
        "classes": ["Sorcerer", "Warlock", "Wizard"],
        "description": "Creates three illusory duplicates of the caster; an attacker often hits a duplicate instead (destroying it) rather than the real caster.",
    },
    "Hold Person": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Artificer", "Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
        "description": "A humanoid target becomes paralyzed on a failed Wisdom save (repeats the save each turn); attacks against a paralyzed target auto-crit within 5 feet.",
    },
    "Spiritual Weapon": {
        "school": "Evocation",
        "casting_time": "1 bonus action",
        "range": "60 feet",
        "duration": "1 minute",
        "classes": ["Cleric"],
        "description": "Conjures a spectral weapon that immediately makes a melee spell attack (1d8 + spellcasting modifier force damage) and can attack again as a bonus action on later turns without recasting.",
    },
    "Aid": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "8 hours",
        "classes": ["Artificer", "Cleric", "Paladin"],
        "description": "Up to three allies gain 5 extra maximum and current hit points for the duration.",
    },
    "Lesser Restoration": {
        "school": "Abjuration",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Ranger"],
        "description": "Ends one disease or one condition (blinded, deafened, paralyzed, or poisoned) affecting a touched creature.",
    },
    "Moonbeam": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "120 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Druid"],
        "description": "A silvery beam of light in an area deals 2d10 radiant damage (Constitution save for half) to creatures there, repeatable each turn the beam is moved onto them.",
    },
    "Flaming Sphere": {
        "school": "Conjuration",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Artificer", "Druid", "Wizard"],
        "description": "A 5-foot sphere of fire that can be rolled into creatures as a bonus action, dealing 2d6 fire damage on a failed Dexterity save.",
    },
    "Suggestion": {
        "school": "Enchantment",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "Concentration, up to 8 hours",
        "classes": ["Bard", "Sorcerer", "Warlock", "Wizard"],
        "description": "Plants a reasonable-sounding course of action in a target's mind on a failed Wisdom save; it follows the suggestion as best it can. Social/utility, not direct damage.",
    },
    "Blindness/Deafness": {
        "school": "Necromancy",
        "casting_time": "1 action",
        "range": "30 feet",
        "duration": "1 minute",
        "classes": ["Artificer", "Bard", "Cleric", "Sorcerer", "Wizard"],
        "description": "A target becomes blinded or deafened (caster's choice) on a failed Constitution save, repeating the save each turn.",
    },
    "Enhance Ability": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "Touch",
        "duration": "Concentration, up to 1 hour",
        "classes": ["Artificer", "Bard", "Cleric", "Druid", "Sorcerer"],
        "description": "A touched creature gains advantage on checks with one chosen ability while concentration holds. No direct combat effect.",
    },
    "Heat Metal": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Artificer", "Bard", "Druid"],
        "description": "Causes a manufactured metal object to glow red-hot; a creature touching/wielding it takes 2d8 fire damage and has disadvantage on attacks/checks until its next turn, repeatable each turn.",
    },
    "Shatter": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Instantaneous",
        "classes": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
        "description": "A thunderous ringing noise in an area deals 3d8 thunder damage (Constitution save for half) -- also especially damaging to inanimate objects/constructs.",
    },
    "Darkness": {
        "school": "Evocation",
        "casting_time": "1 action",
        "range": "60 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Sorcerer", "Warlock", "Wizard"],
        "description": "Magical darkness fills an area, blocking normal darkvision. No direct damage, but a strong battlefield-control option.",
    },
    "Branding Smite": {
        "school": "Evocation",
        "casting_time": "1 bonus action",
        "range": "Self",
        "duration": "Concentration, up to 1 minute",
        "classes": ["Paladin"],
        "description": "The caster's next weapon hit deals an extra 2d6 radiant damage and causes the target to glow with light, negating invisibility, while concentration holds.",
    },
    "Find Steed": {
        "school": "Conjuration",
        "casting_time": "10 minutes",
        "range": "30 feet",
        "duration": "Instantaneous",
        "classes": ["Paladin"],
        "description": "Summons a loyal magical steed (typically a warhorse or similar) to serve as a mount.",
    },
    "Spike Growth": {
        "school": "Transmutation",
        "casting_time": "1 action",
        "range": "150 feet",
        "duration": "Concentration, up to 10 minutes",
        "classes": ["Druid", "Ranger"],
        "description": "Camouflaged spikes fill an area, making it difficult terrain that deals 2d4 piercing damage per 5 feet a creature moves through it.",
    },
}
